server {
    # Define interface:port pairs
    host 127.0.0.1;
    listen 8080;

    server_name localhost;
	root ./www;
    # Set the maximum allowed size for client request bodies
    client_max_body_size 100000;

    # Set up default error pages
    error_page 404 /www/errors/404.html;
    # error_page 500 502 503 504 /www/errors/50x.html;

    # Directory where the requested file should be located
    
    # Default file to serve when the requested resource is a directory
    # index index.html;

    # Route 1: Default location
    location / {
        # List of accepted HTTP methods for the route
       methods GET POST DELETE;
        
        # Enabling or disabling directory listing
        autoindex off;
    }

    # # Route 2: HTTP redirection
    # location /old-page {
    #     return 301 http://127.0.0.1:8080/new-page.html;
    # }

    # Route 3: File upload configuration
    location /upload {
        methods GET POST DELETE;
        autoindex on;
        
        # Uploading files from the clients to the server is authorized, and storage location is provided
        # upload_store ./www/uploads;
    }

    # Route 4: CGI execution based on file extension
    location /cgi-bin {
        methods GET POST DELETE;
		cgi_extension .php; 
        cgi_path ./cgi_tester;
    }
}

server {
    host 0.0.0.0;
    listen 8081;
    server_name localhost;
    
    # 指向一个不同的目录，方便测试时一眼看出请求到了这个服务器
    root ./www_8081; 
    
    # 故意设置得很小，用于测试 curl 报 413 Payload Too Large
    client_max_body_size 10; 

    location / {
        methods GET;
        autoindex on;
    }
}

# server {
#     host 127.0.0.1;
#     listen 8080; # 注意：这里和 Server 1 是同一个端口
#     server_name example.com; # 但是域名不同
    
#     # 指向另一个不同的目录
#     root ./www_example;

#     location / {
#         methods GET;
#         index example.html;
#     }
# }