server {
    host 127.0.0.1;
    listen 8080;
    server_name localhost default.com;
    root ./www/default;
    client_max_body_size 100000;

    location / {
        methods GET;
        autoindex on;
    }
}

# =================================================================
# Server 2: 测试 "different hostnames" (监听 8080 端口)
# 端口和 Server 1 完全一样，但 server_name 是 example.com
# =================================================================
server {
    host 127.0.0.1;
    listen 8080;
    server_name example.com;
    root ./www/example;
    client_max_body_size 100000;

    location / {
        methods GET;
        autoindex off;
    }
}

# =================================================================
# Server 3: 测试 "different ports" (监听 8081 端口)
# =================================================================
server {
    host 127.0.0.1;
    listen 8081;
    server_name localhost;
    root ./www/port8081;
    client_max_body_size 100000;

    location / {
        methods GET;
        autoindex on;
    }
}