server {
	listen 8080;
	server_name localhost;

	client_max_body_size 1048576;

	error_page 404 /404.html;

	location / {
		root ./www;
		index index.html;
		methods GET POST;
		autoindex off;
	}

	location /images {
		root ./www/images;
		autoindex on;
		methods GET;
	}

	location /cgi-bin {
		root ./cgi-bin;
		cgi_extension .py .sh;
		methods GET POST;
	}
}