# Server 1: 默认主服务器 (监听 8080 端口)

server {
    host 127.0.0.1;
    listen 8080;
    server_name localhost;
    
    # 统一使用 ./www 作为根目录，内部的 location 会自动继承
    root ./www;
    client_max_body_size 1048576;
    index index.html;
	error_page 404 /error_pages/404.html;
	error_page 405 /error_pages/405.html;
	error_page 413 /error_pages/413.html;
	error_page 500 /error_pages/500.html;
	error_page 505 /error_pages/505.html;

    location / {
        methods GET POST;
        index index.html;
        autoindex off;
    }

    location /images {
        methods GET;
        autoindex on;
    }

    location /cgi-bin {
        methods GET POST;
        cgi_extension .py;
    }
}

# Server 2: 测试 "different hostnames" (监听 8080 端口)
# 端口和 Server 1 冲突，必须通过 HTTP 头部的 Host: example.com 触发
server {
    host 127.0.0.1;
    listen 8080;
    server_name example.com;
    
    root ./www;
    client_max_body_size 100000;
	error_page 404 /error_pages/404.html;

    location / {
		root ./www/example;
        methods GET;
        autoindex off;
        index index.html;
    }
}

# Server 3: 测试 "different ports" (监听 8081 端口)
server {
    host 127.0.0.1;
    listen 8081;
    server_name localhost;
    
    root ./www/port8081;
    client_max_body_size 100000;
	# error_page 404 /error_pages/404.html；

    location / {
        methods GET;
        autoindex on;
    }
}